apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: syla-yednosti
data:
  DJANGO_DEBUG: "False"
  DJANGO_ALLOWED_HOSTS: "192.168.10.10,localhost,syla-yednosti.local"
  DJANGO_SETTINGS_MODULE: "config.settings.production"
  DB_HOST: "postgres-service"   # ← ім'я Service PostgreSQL у кластері
  DB_PORT: "5432"