apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
  namespace: syla-yednosti
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: 192.168.10.10:5000/syla-yednosti:v1
          command: ["python", "manage.py", "migrate", "--noinput"]
          envFrom:
            - secretRef:
                name: django-secret
            - configMapRef:
                name: django-config